job_id: 6319871
title: Sr. AI Sales Engineer - Cybersecurity
company: 7AI
location: USA
work_type: FULL_TIME
level: Expert/Leader
skills:
  - AI
  - Cybersecurity
  - Ml
company_size: 34 Employees
description: |
  7AI is seeking a **Senior AI Sales Engineer** to join our growing team as a key technical leader. This is a strategic role for a seasoned professional with deep cybersecurity expertise and a passion to learn and advocate for AI. As one of the first senior hires in our go-to-market team, you will play a critical role in shaping how we engage with customers, influence product direction, and scale our technical sales motion.
  
  You will partner closely with Sales, Engineering, Product, and Customer Success teams to drive high-impact engagements with prospects and customers. Youâ€™ll lead technical discovery, design sophisticated solutions, and communicate the business value of our AI-powered cybersecurity platform to both technical and executive stakeholders.
  
  ****Key Responsibilities:****
  - 
  
  Own and lead the technical sales discussions for high-value customer engagements.
  
  - 
  
  Serve as a trusted advisor to senior IT and security executives, deeply understanding their threat landscape and technology environment.
  
  - 
  
  Design and deliver compelling technical demonstrations and POCs that highlight differentiated capabilities of the 7AI platform.
  
  - 
  
  Collaborate with Product and Engineering teams to translate customer feedback into product features and roadmap priorities.
  
  - 
  
  Tailor solutions during Proof of Value to ensure long-term customer success
  
  - 
  
  Mentor and guide junior Sales Engineers, contributing to team development and knowledge sharing.
  
  - 
  
  Represent 7AI at industry conferences, panels, and partner events as a technical subject matter expert.
  
  - 
  
  Drive continuous improvement of pre-sales processes, tools, and documentation to support scale.
  
  ****Requirements:****
  - 
  
  6+ years of experience in cybersecurity-focused Sales Engineering, Solutions Architecture, or similar customer-facing technical roles.
  
  - 
  
  Demonstrated success in complex B2B enterprise sales, preferably in fast-paced startup environments.
  
  - 
  
  Expert-level knowledge of cybersecurity principles, frameworks, and modern threat landscapes.
  
  - 
  
  Experience working with or evangelizing AI/ML technologies within the security domain.
  
  - 
  
  Exceptional communication skills, with the ability to tailor complex technical topics to both engineering teams and executive stakeholders.
  
  - 
  
  Strong leadership presence with a collaborative mindset and a drive to take ownership.
  
  - 
  
  Proven record in scripting / engineering and customization / implementation
industries:
  - Artificial Intelligence
  - Software
  - Cybersecurity
posted_date: 2026-01-22
url: https://builtin.com/job/sr-sales-engineer-cybersecurity/6319871
source: Built In
