job_id: 7120343
title: Senior Software Engineer - Agentic AI Deployment Services
company: Resilinc
location: USA
work_type: FULL_TIME
level: Expert/Leader
skills:
  - Databricks
  - Postgres
  - Python
  - Ray
company_size: 344 Employees
description: |
  **Join the Future of Supply Chain Intelligence — Powered by Agentic AI** 
  
  **
  
  At Resilinc, we’re pioneering intelligent, autonomous systems that redefine supply chain risk management. Our agentic AI helps global enterprises predict disruptions, assess impact, and act in real time — before operations are affected. Named a 2025 Gartner® Magic Quadrant™ Leader, we’re trusted by top companies in life sciences & pharma, aerospace & defense, high tech, and automotive to protect what matters most. Be part of a team that's redefining resilience on a global scale.
  
  But the real power behind Resilinc? Our people. We’re a fully remote, mission-led team making sure life-saving products and critical goods get where they’re needed, fast. We offer the chance to do meaningful work in a collaborative, empowering culture—where you can be an agent of change. Join us to tackle critical global challenges through high-impact work that matters.
  
  Check out this blog to learn more about how we are impacting the world's most critical supply chains. Global Supply Chain Risks 2026: Act Faster | TEC 
  
  Resilinc | Innovation with Purpose. Intelligence with Impact.** 
  
  **
  
  As a Senior Software Engineer** on our Implementation Deployment Services team, you’ll play a central role in building and scaling AI-powered, data-intensive platforms. Your work will span designing new features, optimizing distributed systems, and ensuring rock-solid performance for mission-critical applications. You’ll push the limits of modern data engineering by enhancing APIs, scaling workflows, and tackling challenges around fault tolerance, high availability, and large-scale data processing.
  
  **
  
  Beyond building, you’ll help shape the engineering culture by driving best practices in code quality and ensuring our platforms meet enterprise-grade SLAs. Most importantly, your contributions will directly power the AI-driven transformation of the world’s most prominent companies.
  
  Please note: US citizenship is required.
  
  What You Will Do**
  
  - Participate in customer discussions to address challenges in risk and compliance
  
  - Create novel solutions to customer challenges in a collaborative, iterative fashion
  
  - Integrate and transform diverse datasets 
  
  - Build Agentic solutions leveraging the Resilinc Agent Factory
  
  - Collaborate with core product and engineering team to drive alignment around emerging customer needs
  
  **What You Will Bring**
  
  - Highly skilled at designing and implementing distributed systems, cloud-based API services, and enterprise cloud data platforms
  
  - Proficiency in Python
  
  - Experience with Ray or similar distributed computing frameworks for machine learning workloads
  
  - Exceptional customer-facing skills – can translate complex technical information to a non-technical audience 
  
  - Proven track record developing reliable, high-quality software or services
  
  - Degree in computer science or a related technical field or equivalent work experience
  
  **What Will Make You Stand Out**
  
  - Knowledge of PostgreSQL, Databricks, and other SQL-based database technologies
  
  - Background in data warehouse or data lake architecture and handling large-scale data processing projects
  
  - Expertise in applying machine learning to supply chain or adjacent domains
  
  - Experience building enterprise B2B shipped product
  
  **What's in it for you? **
  
  At Resilinc, we’re fully remote, with plenty of opportunities to connect in person. We provide a culture where ownership, purpose, technical growth and a voice in shaping impactful technology are at our core. Oh, and the perks? Full-stack benefits for health, wealth and wellbeing to keep you thriving. Hit up your talent acquisition contact for a location-specific FAQ. 
  
  Curious to know more about us? Dive in at www.resilinc.ai 
  
  More great news! Resilinc is backed by Vista Equity Partners
  
  *If you are a person with a disability needing assistance with the application process please contact HR@resilinc.com.*
industries:
  - Information Technology
  - Software
posted_date: 2026-01-26
url: https://builtin.com/job/senior-software-engineer-agentic-ai-implementation-deployment-services/7120343
source: Built In
