job_id: 7482740
title: Senior Security Engineer (AI Security)
company: Justworks
location: New York, USA
work_type: FULL_TIME
level: Expert/Leader
skills:
  - Ai Frameworks
  - Go
  - JavaScript
  - Ruby On Rails
company_size: 1,165 Employees
description: |
  ****Who We Are****At Justworks, you’ll enjoy a welcoming and casual environment, great benefits, wellness program offerings, company retreats, and the ability to interact with and learn from leaders in the startup community. We work hard and care about our most prized asset - our people.
  
  We’re helping businesses get off the ground by enabling them to focus on running their business. We solve HR issues. We’re data-driven and never stop iterating. If you’d like to work in a supportive, entrepreneurial environment, are interested in building something meaningful and having fun while doing it, we’d love to hear from you.
  
  We're united by shared goals and shared motivations at Justworks. These are best summed up in our company values, which are reflected in our product and in our team.
  
  Our Values
  
  If this sounds like you, you’ll fit right in.
  ****Who You Are****
  
  Justworks is looking for an experienced, hands-on Senior Security Engineer specializing in AI who will drive and execute the company’s AI strategy and Digital Security’s objectives. Our ideal candidate has extensive experience building and enhancing security solutions of AI systems that defends against unique AI threats. You have hands-on experience evaluating the security of software systems containing AI features and have designed guardrails to protect our data against AI specific threats. You also have a deep understanding of the fundamentals of computing and development/coding with Ruby on Rails, JavaScript and/or other languages. An ideal candidate should also have experience in *Nix environment and the use of common cybersecurity tools.
  ****Your Success Profile********What You Will Work On****
  - Research AI treads, AI threat landscape, AI vulnerabilities and remediations and AI security control advancement.
  
  - Evaluate and assess AI tools and play a critical role in AI system management and governance 
  
  - Evaluate existing AI security controls and identify opportunities to enhance the security posture and software designs
  
  - Collaborate with other security engineers to bring adequate security capabilities to Justworks.
  
  - Provide technical and architectural guidance on AI to product managers, product engineers, and corporate IT on digital security.
  
  - Work with the team to execute and deliver on our AI  roadmap. This will include but won’t be limited to implementing AI security capabilities in AWS and for corporate.  
  
  - Develop AI security architecture and design standards across Justworks applications and infrastructure to promote a standardized set of security requirements, aligning with internal policies.
  
  - Participates in AI R&D projects and major new AI development initiatives to ensure that appropriate security controls are built into systems prior to production cutover.
  
  - Drive process improvement and control implementation projects in coordination with the larger Digital Technology team at Justworks.
  
  - Act as a cross-functional tools and services expert, working with engineering and risk teams to build AI security control requirements
  
  - Help Cyber Defense Operations triage incidents as needed especially related to AI  security within company internal networks as well as in our production environments in AWS.
  
  - Be the champion for AI implementation within Digital Security, assisting various teams to implement AI models to bring effectiveness and efficiency into security controls, security operations and risk management
  ****How You Will Do Your Work****
  
  As a Senior Security Engineer, *how* results are achieved is paramount for your success and ultimately result in our success as an organization. In this role, your foundational knowledge, skills, abilities and personal attributes are anchored in the following:
  
  - **Good judgement **- the exercise of critical thinking, analyzing and assessing problems and implications, identifying patterns, making connections of underlying issues, understanding risks and developing mitigation strategies, and taking ownership of the outcome.
  
  - **Resourcefulness **- taking a can-do approach, even in the face of obstacles and constraints by assessing what’s in front of you and effectively and efficiently optimizing what you have, whether it's working on something new or thinking about how to do something better.
  
  - **Teamwork and communication **- putting our collective best together through documentation, collaboration, relationship-building, listening, empathy, recruiting, and evangelism.
  
  - **Influence and leadership **- fostering a community of knowledge-sharing, collaboration, mentorship, and forward-thinking.
  
  - **Skills and knowledge **- the capacity to actively learn and apply specific domain knowledge, know-how, and best practices to continually enhance and improve.
  
  In addition, all Justworkers focus on aligning their behaviors to our core values known as COGIS. It stands for:
  
  - **Camaraderie** - Day to day you can be seen working together toward a higher purpose. You like to have fun. You’re an active listener, treat people respectfully, and have a strong desire to know and help others.
  
  - **Openness** - Your default is to be open. You're willing to share information, understand other perspectives, and consider new possibilities. You’re curious, ask open questions, and are receptive to thoughts and feedback from others.
  
  - **Grit **- You demonstrate grit by having the courage to commit and persevere. You’re committed, earnest, and dive in to get the job done well with a positive attitude.
  
  - **Integrity** - Simply put, do what you say and say what you'll do. You’re honest and forthright, have a strong moral compass, and strive to match your words with your actions while leading by example. 
  
  - **Simplicity** - Be like Einstein: “Everything should be made as simple as possible, but no simpler.”
  ****Qualifications****
  - 5+ years experience in information security concepts, common technical security controls, and security architecture design principles, ideally in a SaaS environment
  
  - At least 2+ years of hands-on experience in securing AI systems, evaluating AI threats and implementing AI security controls.
  
  - Background as a software engineer, security architect, or security engineer with experience implementing  security controls in AI environments in AWS.
  
  - Experience in setting up and deploying AI engineering tools like vector databases, AI model hosting and monitoring tools and in driving security best practices with AI coding assistants (like Claude Code, Cursor, etc.).
  
  - Solid experience with Secure-SDLC processes and DevSecOps, including secure design, threat modeling, vulnerability management, etc.
  
  - Experience in monitoring AI systems for security threats and vulnerabilities.
  
  - Knowledge of AI/ML technologies, frameworks and platforms.
  
  - Knowledge of regulations and industry best practices related to AI security and data privacy.
  
  - Familiar with secure coding practices and security scanning technologies
  
  - Extensive experience in security architecture, system design, and engineering scalable security solutions in a cloud-native (AWS) environment
  
  - Experience with scripting and automation using languages such as Python, Ruby or Javascript.
  
  - Proven track record as a strong communicator
  
  - Strong analytical skills
  
  - Exceptional organizational skills
  ****Technologies used****
  - Go, Ruby on Rails, Javascript
  
  - AI frameworks like Langchain/LangGraph, AI hosting platforms, AI coding assistants (both open source and commercial) and emerging protocol standards like MCP and Agent-to-Agent Protocol.
  
  - Technical experience with DevOps, Jira, and other agile automation tools
  
  - Ruby on Rails & Javascript
  
  - (Preferred) Security Certifications: CISSP, CISM, CRISC, GIAC, CCSP or CEH
  
  The base wage range for this position based in our New York City Office is targeted at $167,500.00 to $226,300.00 per year.
  
  #LI-Hybrid #LI-CE1
  
  Actual compensation is based on multiple factors that are unique to each candidate, including and not limited to skill set, level of relevant experience, and specific work location.  Salary ranges for positions based in other locations may differ based on the cost of labor in that location. 
  
  For more information about Justworks’ Total Reward Philosophy, including all of the perks and benefits we are proud to offer our team members, please visit Total Rewards @ Justworks. 
  ****Diversity At Justworks****
  
  Justworks is committed to maintaining a workplace where diversity of identity, culture, and life experience is the norm and is celebrated authentically and respected consistently. Diversity in our work, our people, and our product drives creativity and innovation, entrepreneurial leadership and integrity, competitiveness, and collaboration throughout our business and in the market. We depend on our differences to make our team stronger, our workplace more dynamic, and our product accessible to all of our customers.
  
  We’re proud to be an equal opportunity employer open to all qualified applicants regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital or familial status, disability, pregnancy, gender identity or expression, veteran status, genetic information, or any other legally protected status. Justworks is fully dedicated to providing necessary support to candidates with disabilities who may require reasonable accommodations. We also provide reasonable accommodations to employees based on their sincerely held religious beliefs, as well as for other covered reasons consistent with applicable federal, state, and local laws. If you're in need of a reasonable accommodation, please reach out to us at accommodations@justworks.com. Your comfort and success matter to us, and we're here to ensure an inclusive experience.
  
  Our DEIB Report
industries:
  - HR Tech
  - Payments
  - Professional Services
  - Software
posted_date: 2026-01-10
url: https://builtin.com/job/senior-security-engineer-ai-security/7482740
source: Built In
