job_id: 7631480
title: AI Deployment Engineer- Media Partnerships
company: OpenAI
location: New York, USA
work_type: FULL_TIME
level: Expert/Leader
skills:
  - JavaScript
  - Openai Api
  - Python
company_size: 224 Employees
description: |
  **About the team**
  
  The AI Deployment Engineering (ADE) team is responsible for ensuring the safe and effective deployment of Generative AI applications for developers and enterprises. We act as a trusted advisor and thought partner for our customers, working to build an effective backlog of GenAI use cases for their industry and drive them to production through strong technical guidance. As an ADE, you’ll help the world’s most well-known and trusted news organizations transform their business through solutions such as customer service, contextual search, personalization, and novel applications that make use of our newest, most exciting models.
  
  **About the role**
  
  We are looking for a driven solutions leader with a product mindset to partner with our customers and ensure they achieve tangible business value with GenAI. You will pair with senior media leaders to establish a GenAI strategy and identify the highest value applications. You’ll then partner with their engineering and product teams to move from prototype through production. You’ll take a holistic view of their needs and design an enterprise architecture using OpenAI API and other services to maximize customer value. You will collaborate closely with Media Partnerships, Sales, Solutions Engineering, Applied Research, and Product teams, and you will report to the Head of Solutions Architecture, Digital Native.
  
  This role is based in our New York office. We offer relocation support to new employees.
  
  **In this role, you will:**
  
  - 
  
  Collaborate with news organizations around the world - from leading national and global publishers to non-profit, local, and independent newsrooms - to help them implement our technology in a way that benefits their businesses. This work will span newsroom implementations as well as use cases that benefit other parts of their businesses including customer service, internal business operations, marketing, audience development and sales. 
  
  - 
  
  Deeply embed with our most sophisticated and technical platform customers, serving as their technical thought partner in ideating and building novel applications on our API.
  
  - 
  
  Proactively provide guidance to our customers on how to maximize business impact from their applications, accelerating their time to value.
  
  - 
  
  Experiment and prototype solutions with and for your customers.
  
  - 
  
  Forge and manage relationships with our customers’ leadership and stakeholders to ensure their application’s successful deployment and scale.
  
  - 
  
  Contribute to our open-source developer and enterprise resources.
  
  - 
  
  Scale the Solutions Architect function through sharing knowledge, codifying best practices, and publishing notebooks to our internal and external repositories.
  
  - 
  
  Validate, synthesize, and deliver high-signal feedback to the Product, Engineering, and Research teams.
  
  - 
  
  Use your expertise in programming with Python and Javascript.
  
  **You’ll thrive in this role if you:**
  
  - 
  
  Have 5+ years of technical consulting (or equivalent) experience.
  
  - 
  
  Have a deep understanding of news organizations business models, operating models, and their relationships with their readers and customers. 
  
  - 
  
  Are proficient in Python and JavaScript.
  
  - 
  
  Built and/or delivered prototypes on top of our API platform.
  
  - 
  
  Led complex technical projects and programs with many stakeholders.
  
  - 
  
  Can proactively identify opportunities for maximizing our customers’ business value through leveraging the OpenAI API.
  
  - 
  
  Own problems end-to-end, and are willing to pick up whatever knowledge you're missing to get the job done to ensure both your team and our customers succeed.
  
  - 
  
  Have a humble attitude and an eagerness to help others with empathy.
  
  - 
  
  Operate with high horsepower, are adept at frequent context switching and working on multiple projects at once with expansive ownership, and ruthlessly prioritize.
  
  - 
  
  Thrive in dynamic environments and can navigate ambiguity with ease.
  
  **About OpenAI**
  
  OpenAI is an AI research and deployment company dedicated to ensuring that general-purpose artificial intelligence benefits all of humanity. We push the boundaries of the capabilities of AI systems and seek to safely deploy them to the world through our products. AI is an extremely powerful tool that must be created with safety and human needs at its core, and to achieve our mission, we must encompass and value the many different perspectives, voices, and experiences that form the full spectrum of humanity. 
  
  We are an equal opportunity employer, and we do not discriminate on the basis of race, religion, color, national origin, sex, sexual orientation, age, veteran status, disability, genetic information, or other applicable legally protected characteristic. 
  
  For additional information, please see OpenAI’s Affirmative Action and Equal Employment Opportunity Policy Statement.
  
  Background checks for applicants will be administered in accordance with applicable law, and qualified applicants with arrest or conviction records will be considered for employment consistent with those laws, including the San Francisco Fair Chance Ordinance, the Los Angeles County Fair Chance Ordinance for Employers, and the California Fair Chance Act, for US-based candidates. For unincorporated Los Angeles County workers: we reasonably believe that criminal history may have a direct, adverse and negative relationship with the following job duties, potentially resulting in the withdrawal of a conditional offer of employment: protect computer hardware entrusted to you from theft, loss or damage; return all computer hardware in your possession (including the data contained therein) upon termination of employment or end of assignment; and maintain the confidentiality of proprietary, confidential, and non-public information. In addition, job duties require access to secure and protected information technology systems and related data security obligations.
  
  To notify OpenAI that you believe this job posting is non-compliant, please submit a report through this form. No response will be provided to inquiries unrelated to job posting compliance.
  
  We are committed to providing reasonable accommodations to applicants with disabilities, and requests can be made via this link.
  
  OpenAI Global Applicant Privacy Policy
  
  At OpenAI, we believe artificial intelligence has the potential to help people solve immense global challenges, and we want the upside of AI to be widely shared. Join us in shaping the future of technology.
industries:
  - Artificial Intelligence
  - Machine Learning
  - Generative AI
posted_date: 2026-01-24
url: https://builtin.com/job/solutions-architect-media-partnerships/7631480
source: Built In
