job_id: 7722465
title: Sr AI/HPC Applications and Performance Engineer
company: Hewlett Packard Enterprise
location: 
work_type: FULL_TIME
level: Expert/Leader
skills:
  - AI
  - Cloud Architectures
  - DevOps
  - Distributed Computing
  - Full Stack Development
  - Hpc
  - Microservices
description: |
  Sr AI/HPC Applications and Performance Engineer
  
    
  
  This role has been designed as ‘Hybrid’ with an expectation that you will work on average 2 days per week from an HPE office.
  
  **Who We Are:**
  
  Hewlett Packard Enterprise is the global edge-to-cloud company advancing the way people live and work. We help companies connect, protect, analyze, and act on their data and applications wherever they live, from edge to cloud, so they can turn insights into outcomes at the speed required to thrive in today’s complex world. Our culture thrives on finding new and better ways to accelerate what’s next. We know varied backgrounds are valued and succeed here. We have the flexibility to manage our work and personal needs. We make bold moves, together, and are a force for good. If you are looking to stretch and grow your career our culture will embrace you. Open up opportunities with HPE.
  
  **Job Description:**
  
     
  
  ***Responsibilities:***
  
  - Develops organization-wide architectures, strategies, and methodologies for software systems design and development across multiple platforms and organizations within the Global Business Unit.
  
  - Identifies and makes informed recommendations regarding new technologies, innovations, and outsourced development partner relationships for alignment with technology roadmap and business value; creates plans for integration and update into architecture.
  
  - Reviews, evaluates, and influences designs and project activities for compliance with development guidelines and standards.
  
  - Provides tangible solutions that improve product quality and mitigate failure risk.
  
  - Contributes to domain expertise, business acumen, and experience to influence decisions of executive business leadership, outsourced development partners, and industry standards groups.
  
  - Brings creativity and innovation to the organization.
  
  - Provides guidance and mentoring to less-experienced team members to set an example of software systems design and development innovation and excellence; helps mentor career growth.
  
  - Acts as an internal authority on software systems design, sought out for consulting across organizations or Business Units.
  
  - Contributes to the external technical community through whitepapers, patents, or other significant innovations.
  
  ***Education and Experience Required:***
  
  - **Must have 15+ years’ experience.**
  
  - Deep expertise in** AI and HPC applications and performance engineering including simulation, modeling and emulation capabilities**
  
  - Expertise in** large-scale AI and HPC systems**
  
  - Experience **architecting, designing, and developing innovative software system design tools and languages.**
  
  - Excellent analytical and problem-solving skills.
  
  - Experience in leading overall architecture of software systems for products and solutions.
  
  - Designing and integrating efficient and scalable software systems running on multiple platform types into overall architecture.
  
  - Evaluating and selecting forms and processes for software systems testing and methodology, including writing and execution of test plans, debugging, and testing scripts and tools with customer mindset.
  
  - History of innovation with multiple patents or deployed solutions in the field of software design.
  
  - Excellent written and verbal communication skills; mastery in English with an excellent ability to communicate nuanced concepts and influence in written and oral communication with a broad vocabulary.
  
  - Ability to effectively communicate product architectures, design proposals, and negotiate and influence options at business unit and executive levels.
  
  - Bachelor’s or master’s degree in computer science, Information Systems, or equivalent.
  
  **Additional Skills:**
  Cloud Architectures, Cross Domain Knowledge, Design Thinking, Development Fundamentals, DevOps, Distributed Computing, Microservices Fluency, Full Stack Development, Security-First Mindset, Solutions Design, Testing & Automation, User Experience (UX)
  
  **What We Can Offer You:**
  
  **Health & Wellbeing**
  
  We strive to provide our team members and their loved ones with a comprehensive suite of benefits that supports their physical, financial and emotional wellbeing.
  
  **Personal & Professional Development**
  
  We also invest in your career because the better you are, the better we all are. We have specific programs catered to helping you reach any career goals you have — whether you want to become a knowledge expert in your field or apply your skills to another division.
  
  **Unconditional Inclusion**
  
  We are unconditionally inclusive in the way we work and celebrate individual uniqueness. We know varied backgrounds are valued and succeed here. We have the flexibility to manage our work and personal needs. We make bold moves, together, and are a force for good.
  
  **Let's Stay Connected:**
  
  Follow @HPECareers on Instagram to see the latest on people, culture and tech at HPE. 
  
  #unitedstates********
  
  **Job:**
  Engineering
  
  **Job Level:**
  TCP_06
  
      
  
  **States with Pay Range Requirement**
  
  The expected salary/wage range for a U.S.-based hire filling this position is provided below. Actual offer may vary from this range based upon geographic location, work experience, education/training, and/or skill level. If this is a sales role, then the listed salary range reflects combined base salary and target-level sales compensation pay. If this is a non-sales role, then the listed salary range reflects base salary only. Variable incentives may also be offered. Information about employee benefits offered can be found at https://myhperewards.com/main/new-hire-enrollment.html.
  
  USD Annual Salary: $161,500.00 - $370,500.00
  
  HPE is an Equal Employment Opportunity/ Veterans/Disabled/LGBT employer. We do not discriminate on the basis of race, gender, or any other protected category, and all decisions we make are made on the basis of qualifications, merit, and business need. Our goal is to be one global team that is representative of our customers, in an inclusive environment where we can continue to innovate and grow together. Please click here: Equal Employment Opportunity.
  
  **Hewlett Packard Enterprise is EEO Protected Veteran/ Individual with Disabilities.**
  
     
  
  HPE will comply with all applicable laws related to employer use of arrest and conviction records, including laws requiring employers to consider for employment qualified applicants with criminal histories.
  
     
  
  **No Fees Notice & Recruitment Fraud Disclaimer**
  
  ** **
  
  *It has come to HPE’s attention that there has been an increase in recruitment fraud whereby scammer impersonate HPE or HPE-authorized recruiting agencies and offer fake employment opportunities to candidates.  These scammers often seek to obtain personal information or money from candidates.*
  
   
  
  *Please note that Hewlett Packard Enterprise (HPE), its direct and indirect subsidiaries and affiliated companies, and its authorized recruitment agencies/vendors **will never charge any candidate a registration fee, hiring fee, or any other fee in connection with its recruitment and hiring process.  **The credentials of any hiring agency that claims to be working with HPE for recruitment of talent should be verified by candidates and candidates shall be solely responsible to conduct such verification. Any candidate/individual who relies on the erroneous representations made by fraudulent employment agencies does so at their own risk, and HPE disclaims liability for any damages or claims that may result from any such communication.*
industries:
  - Artificial Intelligence
  - Cloud
  - Information Technology
  - Consulting
posted_date: 2026-02-03
url: https://www.builtinla.com/job/sr-ai-hpc-applications-and-performance-engineer/7722465
source: Built In
