job_id: 7777666
title: Senior IT Engineer (AI & Automation)
company: Headway
location: 
work_type: FULL_TIME
level: Expert/Leader
skills:
  - 1Password
  - AI
  - Atlassian Intelligence
  - Chromeos
  - Confluence
  - Gemini
  - Glean
  - Gmail
  - Google Workspace
  - Intune
company_size: 819 Employees
description: |
  Headway’s mission is a big one – to build a new mental
  health care system everyone can access. We’ve built
  technology that helps people find great therapists with the
  first software-enabled national network of providers
  accepting insurance.
  
  1 in 4 people in the US have a treatable mental health
  condition, but the majority of providers don’t accept
  insurance, making therapy too expensive for most people.
  Headway is building a new mental healthcare system that
  everyone can access by making it easy for therapists to
  accept insurance and scale their practice.
  
  Headway was founded in 2019. Since then, we’ve grown into a
  diverse, national network of over 60,000 mental healthcare
  providers across all 50 states who run their practice on our
  software and have served over 1 million patients. We’re a
  Series D company with over $325m in funding from a16z
  (Andreessen Horowitz), Accel, GV (formerly Google Ventures),
  Spark Capital, Thrive Capital, Forerunner Ventures and
  Health Care Service Corporation.
  
  We want your time here to be the most meaningful experience
  of your career. Join us, and help change mental healthcare
  for the better.
  
  About the role:
  
  Building a new mental healthcare system at Headway is only
  possible because of the scale and leverage that software can
  provide.   The IT team at Headway is an essential function
  at Headway that builds operational efficiency into
  everything we do, giving our organization the tools needed
  to achieve our goals of reshaping mental healthcare.   In
  this role, you’ll have the unique opportunity to build the
  foundations of productivity engineering at Headway.
  Building and maintaining systems to enable efficiency across
  our organization through the implementation of AI and
  Automation.
  
  You’ll love this role if you want to:
  
  - Use AL, LLMs, and agentic automation to solve meaningful
    operational problems across the company.
  - You get energy from architecting and shipping scalable
    workflows while diving into new technologies such as AI.
  - You enjoy building internal tools from scratch, not just
    configuring out-of-the-box features.
  - You care about reliability—adding observability, structured
    error handling, and testing frameworks so automations
    behave like production software.
  - You want to create reusable frameworks, templates, and
    patterns so future workflows can be built faster and more
    consistently—not one-off scripts.
  - You love partnering closely with internal teams to
    understand their needs and translate them into solutions
    that materially increase speed and efficiency.
  - You think in systems, not tasks—and want to design
    foundations that scale as the company grows.
  
  You may be a good fit if you:
  
  - Architect, build, and deploy scalable workflow automations
    and integrations across core business systems using
    AI/LLMs and agentic automation.
  - Design, build, and maintain custom internal tools leveraging
    APIs and cross-platform automation tools.
  - Implement error handling and observability for automations
    and internal tools.
  - Develop automation templates/standards and frameworks that
    enable future workflows to be created rapidly and with
    consistency.
  - Develop testing frameworks for automated workflows to ensure
    quality, reliability, and resilience.
  - Develop longitudinal relationships across Headway and
    partner with stakeholders to design and implement
    automated solutions to enable Headway teams to work with
    speed.
  
  Tools we use:
  
  - AI Tools: Gemini, Glean, Slack AI, Atlassian Intelligence
  - Identity and Access Management: Okta, Lumos
  - Email and Messaging: Gmail and Slack
  - Document Creation and Collaboration: Google Workspace,
    Confluence
  - Credential Management: 1Password
  - Ticketing: Jira Service Desk, ZenDesk, Jira Projects
  - Project Planning: Jira
  - Endpoint Management: JAMF, InTune, ChromeOS, Kolide
  
  Our interview process
  
  After you apply to Headway, here are some details of what to
  expect during the interview process.
  
  - Initial screen: You’ll connect with someone in recruiting so
    you can learn more about the team, Headway’s mission and
    exciting growth, and we can get a better idea of your
    background.
  - First round: You'll meet with the IT Manager to discuss your
    previous experience, and do an initial technical screen.
  - Final rounds: You’ll meet several team members for technical
    and non-technical interviews, and leave with a fuller
    picture of what it’s like to work at Headway.
  - References and the Offer: Our favorite part of the process!
    We'll send over all of the details, including specifics on
    employee equity, and congratulatory messages from excited
    future team members!
  
  Compensation and Benefits:
  
  The expected base pay range for this position is $152,000 -
  $190,000, based on a variety of factors including
  qualifications, experience, and geographic location. In
  addition to base salary, this role may be eligible for an
  equity grant, depending on the position and level.
  
  We are committed to offering a comprehensive and competitive
  total rewards package, including robust health and wellness
  benefits, retirement savings, and meaningful ownership
  opportunities through equity. Compensation decisions are
  made holistically, ensuring fairness and alignment with
  market benchmarks while recognizing individual contributions
  and potential.
  
  - Benefits offered include:
  
  #LI-EM1
  
  We believe a team's strength is in its people, and we cannot
  achieve this mission without a team that reflects the
  diversity of this problem – across race, ethnicity, gender,
  sexuality, age, national origin, religion, family status,
  disability, military status, and experience. Headway is
  committed to the full inclusion of all qualified
  individuals. As part of this commitment, Headway will ensure
  that persons with disabilities are provided with reasonable
  accommodations. If reasonable accommodation is needed to
  participate in the job application or interview process, to
  perform essential job functions, and/or receive other
  benefits and privileges of employment, please inform the
  recruiter when they contact you to schedule your interview.
  
  Headway participates in E-Verify. To learn more, click here.
  
  A notice to Headway applicants: To protect yourself against
  phishing and recruitment fraud, please note that Headway
  only accepts applications through our official careers page
  at https://headway.co/careers. Headway will never refer you
  to external websites, ask for payment or personal
  information, or conduct interviews via messaging apps. All
  official communication will come from a @findheadway.com
  email address. If you are contacted by someone claiming to
  be from Headway via an unofficial channel, please do not
  share any information and report it as spam.
industries:
  - Consumer Web
  - Healthtech
  - Professional Services
  - Social Impact
  - Software
posted_date: 2026-01-12
url: https://builtin.com/job/senior-it-engineer-ai-automation/7777666
source: Built In
