job_id: 8133686
title: Sr Application Engineer (Salesforce Agentforce AI)
company: PointClickCare
location: USA
work_type: FULL_TIME
level: Expert/Leader
skills:
  - Agentforce
  - AI
  - Alteryx
  - Angular
  - Apex
  - AWS
  - Azure
  - Copado
  - DevOps
  - Git
company_size: 1,557 Employees
description: |
  At PointClickCare our mission is simple: to help providers
  deliver exceptional care. And that starts with our people.
  As a leading health tech company that’s founder-led and
  privately held, we empower our employees to push boundaries,
  innovate, and shape the future of healthcare.
  
  With the largest long-term and post-acute care dataset and a
  Marketplace of 400+ integrated partners, our platform serves
  over 30,000 provider organizations, making a real difference
  in millions of lives. We also reinvest a significant
  percentage of our revenue back into research and
  development, ensuring our employees have the resources to
  innovate and make a lasting impact. Recognized by Forbes as
  a top private cloud company and honored as one of Canada’s
  Most Admired Corporate Cultures, we offer flexibility,
  growth opportunities, and meaningful work.
  
   At PointClickCare, we empower our people to be the
  architects of a smarter healthcare future; one that is
  human-first and accelerated by AI to create meaningful and
  lasting change. Employees harness AI as a catalyst for
  creativity, productivity, and thoughtful decision-making. By
  integrating AI tools into our daily workflows, collaboration
  is enhanced, outcomes are improved, and every team member
  has the proficiency to maximize their impact. It all starts
  with our hiring practices where we uncover AI expertise that
  complements our mission, and we continue to invest in
  training and development to nurture innovation throughout
  the employee journey.
  
  Join us in redefining healthcare — so it doesn’t just
  survive, it thrives. To learn more about PointClickCare,
  check out Life at PointClickCare and connect with us on
  Glassdoor and LinkedIn.
  
  **Travel to Office expectations**
  
  For Remote Roles: If this role is remote, there will be in-
  office events that will require travel to and from the
  Mississauga and/or Salt Lake City office. These will
  include, but not limited to, onboarding, team events, semi-
  annual and annual team meetings.
  
  For Hybrid Roles: If this role is Hybrid, there will be an
  expectation to reside within commutable distance to the
  office/location specified in the job listing. This will
  include, but not limited to, weekly/bi-weekly/monthly events
  in the office with your specific team. This is a requirement
  for this role.
  
  Job Summary
  
  We’re looking for creative thinkers with hands-on experience
  in Agentforce, AI agent development, and intelligent process
  automation, who thrive in a collaborative, fast-paced
  environment. As a Senior Application Engineer specializing
  in Salesforce Agentforce AI at PointClickCare, you’ll
  architect and deliver state-of-the-art AI agents and
  automations that transform system workflows. You’ll be
  empowered to experiment, prototype, and deliver solutions
  that directly shape the future of our technology landscape,
  gain exposure to the latest AI technologies and dedicated
  time for professional development and certifications as you
  create AI Agents using Agentforce and other AI tools.
  
  To succeed in this role, you need to be an autonomous and
  accountable team player with a continuous learning mindset
  and understand what it means to be a member of a high
  performing team. You bring hands-on experience building
  Agentforce AI Agents and over 5 years of experience and
  knowledge designing, developing, and maintaining
  configuration and custom applications that integrate with
  Salesforce or other connected apps.
  
  As a Senior Application Engineer (Salesforce Agentforce AI)
  at PointClickCare you will also build intelligent process
  automations, test automations, and debug standard to complex
  issues related with Apex code, JavaScript, Python or code
  from other programming languages as it relates to the
  applications you are developing for. You will develop
  technical documentation, be part of our DevOps maintenance
  crew and peer review builds developed by other team members
  and vendors. You will provide training and consultation
  related to the systems and processes developed by the team
  to our business partners and support both transformational
  projects, high priority enhancements and resolve standard to
  high complexity incidents to quickly deliver value to the
  business.
  
  What your day-to-day will look like
  
  •Work at the forefront of AI-driven Salesforce solutions and
  build AI Agents using Agentforce, and other AI platforms
  like Microsoft Studio for CoPilot Agents.
  
  •Pioneer intelligent automations in enterprise environments
  using IPA tools like Power Automate, Alteryx, and others.
  
  •Build test automations to improve QA efficiencies in QA for
  Salesforce and other applications.
  
  •Collaborate with product designers, end-users, and other
  team members to refine and understand outcomes and AI use
  cases.
  
  •Collaborate with other team members to brainstorm ideas for
  prototyping to test and solution for use cases identified
  and prioritized.
  
  •Execute standard to complex tasks in the application
  development life cycle using languages like Apex,
  JavaScript, Python, etc., etc., relevant to the core
  applications (Salesforce, Billing Platform, etc.) and
  connected or integrated apps (Conga, Docusign, Adobe,
  Marketo, Gainsight, Gong, Qualtrics, Kantata, TaskRay,
  etc.).
  
  •Perform unit tests for your builds and collaborate with
  Product Designers and other team members to create accurate
  and quality test scripts for automated and manual testing.
  
  •Analyze, troubleshoot, and debug systems for standard
  issues
  
  •Be an AI change agent in your team to gain team buy-in for
  adopting use of AI agents to save time, reduce waste and
  improve efficiency to deliver value to customers faster
  
  •Create and maintain technical documentation for all builds
  and AI Agents produced
  
  •Onboard, mentor and coach Junior - Intermediate application
  engineers and your peers – including peer reviewing their
  work, providing feedback, approving pull requests and
  providing guidance as needed.
  
  •Perform other tasks and duties as assigned
  
  Qualifications we are looking for
  
  •Hands-on experience building Agentforce AI Agents, AI
  workflows, custom agent development, and integration of
  external data sources.
  
  •Experience creating intelligent process automations using
  tools like Power Automate or others
  
  •Solid experience creating test automations for Salesforce
  and other platforms
  
  •Solid experience writing clean code that performs well at
  scale using JavaScript, Apex, Python, etc.
  
  •Solid experience with Salesforce integrations and external
  system integrations (Conga, Docusign, Adobe, Marketo,
  Gainsight, Gong, Qualtrics, Kantata, TaskRay, etc.)
  
  •Proficient in DevOps processes and tools (e.g., Copado,
  AutoRabit)
  
  •Proficient in GITHUB and troubleshooting standard
  versioning and DevOps issues
  
  •Proficient in Agile methodologies (Scrum/Kanban) to
  iteratively deliver standard solutions
  
  •Solid experience with automated testing frameworks (e.g.
  PMD, Selenium, Copado CRT)
  
  •In-depth understanding of Salesforce data models, security,
  and governor limits
  
  •Excellent organization, critical-thinking and self-
  management skills
  
  •A continuous learner – you must enjoy acquiring and sharing
  knowledge and wisdom with others
  
  •Solid Team player and coach to partner with cross-
  functional teams and other areas of practice like BA, QA &
  Operations
  
  •Communicates standard - complex ideas, anticipates
  potential objections and persuades others, often at team
  level, to adopt a different point of view
  
  •Proven experience as a great Intermediate Application
  Engineer
  
  •Certifications:
  
  oSalesforce Certified Agentforce Specialist
  
  oSalesforce Certified Platform Developer I & II (required)
  
  oSalesforce Advanced Administrator certification (required)
  
  oSalesforce Certified Application/Systems Architect
  (desired)
  
  •BSc/BA in Computer Science, Engineering, or a related field
  (or equivalent work experience)
  
  Bonus points for:
  
  •Experience building AI Agents on other AI Platforms
  
  •Experience being part teams that operated using the Product
  Operating Model
  
  •Experience working on a SaaS product
  
  •Experience with Salesforce Lightning Design System (SLDS)
  or other UI frameworks like React, Vue.js, or Angular
  
  •Standard understanding of Salesforce Sales Cloud, Service
  Cloud, Revenue Cloud, Agentforce, and Salesforce Einstein
  
  •Experience working with AWS, Azure, or other cloud
  platforms.
  
  •Experience working with Service-Oriented Architecture (SOA)
  and SaaS product development
  
  •Knowledge of SAML, OAuth, and OpenID Connect for
  authentication and authorization
  
  •Experience with on-call responsibilities for production-
  grade systems.
  
  •Understanding how to solve the dysfunctions of a team
  (trust, conflict, commitment, accountability and team
  results)
  
  PointClickCare Benefits & Perks:
  
  Benefits starting from Day 1!
  
  Retirement Plan Matching
  
  Flexible Paid Time Off
  
  Wellness Support Programs and Resources
  
  Parental & Caregiver Leaves
  
  Fertility & Adoption Support
  
  Continuous Development Support Program
  
  Employee Assistance Program
  
  Allyship and Inclusion Communities
  
  Employee Recognition … and more!
  
  It is the policy of PointClickCare to ensure equal
  employment opportunity without discrimination or harassment
  on the basis of race, religion, national origin, status,
  age, sex, sexual orientation, gender identity or expression,
  marital or domestic/civil partnership status, disability,
  veteran status, genetic information, or any other basis
  protected by law. PointClickCare welcomes and encourages
  applications from people with disabilities. Accommodations
  are available upon request for candidates taking part in all
  aspects of the selection process. Please contact
  recruitment@pointclickcare.com should you require any
  accommodations. As part of our commitment to a streamlined
  and equitable hiring experience, PointClickCare uses AI
  tools to assist with candidate screening and assessment.
  
  When you apply for a position, your information is processed
  and stored with Lever, in accordance with Lever’s Privacy
  Policy. We use this information to evaluate your candidacy
  for the posted position. We also store this information, and
  may use it in relation to future positions to which you
  apply, or which we believe may be relevant to you given your
  background. When we have no ongoing legitimate business need
  to process your information, we will either delete or
  anonymize it.  If you have any questions about how
  PointClickCare uses or processes your information, or if you
  would like to ask to access, correct, or delete your
  information, please contact PointClickCare’s human resources
  team: recruitment@pointclickcare.com
  
  PointClickCare is committed to Information Security. By
  applying to this position, if hired, you commit to following
  our information security policies and procedures and making
  every effort to secure confidential and/or sensitive
  information.
industries:
  - Healthtech
  - Software
posted_date: 2026-02-03
url: https://builtin.com/job/sr-application-engineer-salesforce-agentforce-ai/8133686
source: Built In
