job_id: 8293494
title: AI Applications Engineer (Glen Cove, NY)
company: Standard Bots
location: Glen Cove, USA
work_type: FULL_TIME
level: Expert/Leader
skills:
  - AI
  - Python
  - Robotics
  - Solidworks
company_size: 55 Employees
description: |
  About Standard Bots
  
  Standard Bot’s mission is to significantly lower the barrier
  to entry to real-world automation, bringing the power of
  bits to the world of atoms and unlocking productivity for
  entire new industries and users.
  
  Our user facing applications and APIs unlock the power of
  automation for entire new use cases. A relentless focus on
  simplicity and ease of use brings the revolutionary
  potential of robotic automation to new users and industries.
  The Applications Engineering team drives forward the
  company’s mission by designing solutions around, installing
  and supporting Standard Bot’s innovative 6 axis robot.
  
  Notes: This role will be required to come into our Glen Cove
  robotics factory 4-5 days/week and could require up to 40%
  travel
  
  We are unable to offer Visa sponsorship for this role
  
  What You’ll Do:
  
  We’re looking for seasoned and skilled customer facing
  problem-solvers to help architect the future of robotics
  through the design, installation and support of innovative
  new robotic solutions. As an Applications Engineer, you will
  work with other engineers, organizational leaders, sales and
  customers to design, install and support solutions for our
  customers in new and exciting robotic applications.
  
  Responsibilities:
  
  - Support groundbreaking AI work at the leader of AI
    integrated Robotics based right in New York
  - Work with sales and our customers to design solutions around
    the Standard Bots RO1 for AI enabled applications
  - See the process through by going into the field to install,
    program and verify Standard Bots AI solutions
  - Support our customers as they find new and innovative ways
    to use Standard Bot’s RO1 AI functionality
  - Develop proof of concept system to show Standard Bot’s
    capabilities at our AI lab in Glen Cove, NY
  - Develop supporting materials such as sample code, white
    papers and application notes
  - Assist in-house engineering with the design and testing of
    ever-expanding AI functionality
  - Develop marketing collateral to assist with growing the
    Standard Bot’s customer base
  - Ability to be in the Glen Cove, NY office 4-5 days per week
  
  Who You Are:
  
  We’re looking for engineers who are self driven, optimistic,
  creative, and resourceful. We have no requirements for a
  background in robotics, but find most success with engineers
  excited by the domain and looking to apply their expertise
  and experience in a new area.
  
  Skills you’ll bring:
  
  - Experience: You have a strong technical background,
    including 5+ years working in complex environments or
    relevant educational experience in automation including
    basic electrical, programming and mechanical — you're
    comfortable with DC power, know the difference between NPN
    and PNP, can write python scripts, and can navigate
    Solidworks
  - Growth + Optimism: You are excited by new domains and
    challenges, and eager to pick up new context to accelerate
    your impact
  - Clarity of Communication: You excel in written and verbal
    communication and enjoy leveraging your skills to support
    your peers
  - Impact Driven: You relentlessly seek user impact and value
    execution over technical idealism
  - Proactive Simplicity: You prioritize simplicity,
    reliability, and velocity and proactively identify
    opportunities to improve proposed implementations or
    incumbent systems
  - Excelling in Ambitious Environments: You excel in dynamic
    and ambitious environments, working with a diverse group
    of individuals and backgrounds
  
  Compensation and Benefits:
  
  The salary range for this role is $80,000 to $150,000,
  depending on experience. We are open to a variety of
  seniority levels for this role and will build compensation
  packages that are commensurate with seniority and skill
  level. Base salary is just one part of the overall
  compensation at Standard Bots. All Full-Time Employees are
  eligible for Employee Stock Options. We also offer a package
  of benefits including paid time off, medical/dental/vision
  insurance, life insurance, disability insurance, and 401(k)
  to regular full-time employees.
industries:
  - Artificial Intelligence
  - Productivity
  - Robotics
  - Industrial
  - Generative AI
  - Automation
  - Manufacturing
posted_date: 2026-01-23
url: https://builtin.com/job/ai-applications-engineer-glen-cove-ny/8293494
source: Built In
