job_id: 8342705
title: Principal AI Deployment Engineer
company: Howden Re
location: London, GBR
work_type: FULL_TIME
level: Senior level
skills:
  - APIs
  - Azure
  - Azure Bicep
  - Microservices
  - Python
  - Rag Infrastructures
  - Terraform
  - Vector Databases
company_size: 658 Employees
description: |
  **Who are we?**
  
  Howden is a global insurance group with employee ownership at its heart. Together, we have pushed the boundaries of insurance. We are united by a shared passion and no-limits mindset, and our strength lies in our ability to collaborate as a powerful international team comprised of 23,000 employees spanning over 56 countries.
  
  People join Howden for many different reasons, but they stay for the same one: our culture. It’s what sets us apart, and the reason our employees have been turning down headhunters for years. Whatever your priorities – work / life balance, career progression, sustainability, volunteering – you’ll find like-minded people driving change at Howden.
  
  **About The Role**
  
  Howden Group Services is expanding its AI & Data Science capabilities and is looking for an AI Deployment Engineer to help accelerate our transformation and build enterprise-grade solutions with AI at their core that will be used by hundreds of colleagues across the Group.
  
  You will have a dual reporting line into the Group Head of Data Science and the Group Head of Data Operations and will bring deep technical expertise on cloud engineering and SRE with a focus on AI applications. You will be given freedom to experiment, test and bring new technologies that push the envelope on using AI to solve enterprise problems and apply them to the complex business domain of commercial insurance.
  
  **Role Responsibilities **
  
  - 
  
  Design and develop scalable and secure infrastructure and CI/CD pipelines for AI solutions
  
  - 
  
  Engineer and maintain production-ready RAG infrastructures and Vector Databases for our AI use cases and implement efficient retrieval strategies for data
  
  - 
  
  Work with our AI Engineers and Data Scientists to develop and maintain a highly reliable Model Serving Layer and make our models available as scalable and reliable services, including for LLM access
  
  - 
  
  Act as a technical and platform authority for AI Solutions and provide thought leadership to the rest of the Data Science and Data Platform team on the latest AI technologies and solutions
  
  - 
  
  Engineer and maintain infrastructure and data pipelines for custom model fine-tuning
  
  - 
  
  Implement and manage standardised Agent Frameworks, multi-agent systems and autonomous decision-making frameworks
  
  - 
  
  Work with AI Engineers and Data Scientists to build appropriate observability, logging and monitoring solutions for our AI use cases, including model performance KPIs, token usage, drift and hallucination detection
  
  - 
  
  Develop, build and maintain the Howden Enterprise AI Platform, including robust security, networking, and access strategies
  
  - 
  
  Implement a robust FinOps framework for our AI use cases allowing for precise cost controls and chargebacks
  
  - 
  
  Contribute to an excellent developer experience by building robust SDKs, APIs as well as drafting clear documentation and knowledge-sharing artefacts
  
  **Your Skills **
  
  - 
  
  3-5 years of experience in Software Engineering with a focus of MLOps
  
  - 
  
  Track record of shipping production ML and AI systems at scale in enterprise environments
  
  - 
  
  Deep knowledge of cloud infrastructure (Azure preferred) and infrastructure as code (Terraform, Azure Bicep etc)
  
  - 
  
  Excellent proficiency in Python and developing robust and scalable APIs and microservices
  
  - 
  
  A working understanding of LLM architectures, MLOps and AIOps architectures including optimising complex RAG pipelines using vector databases (e.g. PGVector)
  
  - 
  
  An interest and some hands-on experience with agentic frameworks
  
  - 
  
  A demonstrable track record of designing simple and efficient technical solutions and infrastructure. Bonus points for implementing cost-saving measures in large-scale cloud deployments and/or large organisations with multiple user groups
  
  At Howden, we are looking to build a diverse team and promote the development of individuals of all backgrounds. If you have experience of mentoring and coaching others, we’d encourage you to apply if you meet the majority of these requirements and are driven by learning, developing and picking up the required skills to make you successful in your role.
  
  **Core Responsibilities for all Staff**
  
  **Achieve Results through Relationships with All Parties**
  
  - 
  
  Deliver a personal performance that contributes towards Group and/or Company achieving their objectives.
  
  - 
  
  Achieve lasting relationships with all parties (internal clients, suppliers, third parties and other staff).
  
  **Delivery of Service**
  
  - 
  
  Consistently deliver an excellent and comprehensive service, on-time, within budget and to, or exceeding quality expectations.
  
  **Conduct and Integrity**
  
  - 
  
  Ensure all dealings are carried out with integrity and professionalism.
  
  - 
  
  Act in utmost good faith, in accordance with Group and/or Company policies and never risk the Company’s or the Group’s reputation.
  
  **Reporting**
  - 
  
  Monitor and report on Business Units’ issues.
  
  - 
  
  Provide relevant management information to senior management.
  
  - 
  
  Any other reasonable duties, as required.
  
  **What do we offer in return?**
  
  A career that you define. At Howden, we value diversity – there is no one Howden type. Instead, we’re looking for individuals who share the same values as us:
  
  - 
  
  Our successes have all come from someone brave enough to try something new
  
  - 
  
  We support each other in the small everyday moments and the bigger challenges
  
  - 
  
  We are determined to make a positive difference at work and beyond
  
  ******Reasonable adjustments**
  
  We're committed to providing reasonable accommodations at Howden to ensure that our positions align well with your needs.  Besides the usual adjustments such as software, IT, and office setups, we can also accommodate other changes such as flexible hours* or hybrid working*.
  
  If you're excited by this role but have some doubts about whether it’s the right fit for you, send us your application – if your profile fits the role’s criteria, we will be in touch to assist in helping to get you set up with any reasonable adjustments you may require.
  
  *Not all positions can accommodate changes to working hours or locations. Reach out to your Recruitment Partner if you want to know more.
  Permanent
posted_date: 2026-01-29
url: https://builtin.com/job/principal-ai-deployment-engineer/8342705
source: Built In
