job_id: 4802406
title: Senior AI Applications Engineer
company: Ema Unlimited
location: Bengaluru, IND
work_type: FULL_TIME
level: Expert/Leader
skills:
  - AI
  - Genai
  - JSON
  - Llm
  - Python
  - Rest
  - Soap
  - SQL
company_size: 78 Employees
description: |
  Who are we?
  
  Ema is building the next generation AI technology to empower
  every employee in the enterprise to be their most creative
  and productive. Our proprietary tech allows enterprises to
  delegate most repetitive tasks to Ema, the Universal AI
  employee. We are founded by ex-Google, Coinbase, Okta
  executives, and serial entrepreneurs. We’re well-funded by
  the top investors and angels in the world. Ema is based in
  Silicon Valley and Bangalore.
  
  Who are you?
  
  The Senior AI Application Engineer will be pivotal in
  providing world-class post-deployment support for Ema’s
  Agent Assist/Chatbot product. This role requires a strong
  blend of technical expertise and customer-focused problem-
  solving. You will configure, troubleshoot, and optimize AI
  solutions for our customers, ensuring high performance,
  continuous improvement of customer workflows, and
  exceptional customer satisfaction. You will independently
  manage complex deployments and solutions for enterprise
  customers with minimal guidance.
  
  You will:
  
  Roles and Responsibilities
  
  - Configure and integrate AI/GenAI workflows using platform
    APIs and customer data, ensuring smooth and secure
    deployment.
  - Translate customer requirements into technical solutions,
    validating workflow correctness and continuously refining
    prompts for optimal performance.
  - Develop and automate tasks using Python & SQL, and build
    prototypes using open-source Agentic Frameworks to
    streamline CX workflows.
  - Design, run, and analyze A/A experiments to measure and
    improve workflow quality and reliability.
  - Monitor AI workflows using business metrics and
    observability dashboards, quickly responding to issues to
    ensure high availability.
  - Provide proactive solutions and regular updates to
    customers, maintaining high CSAT through effective
    troubleshooting and communication.
  - Diagnose and resolve platform issues related to APIs, data
    integration, and workflow configurations, collaborating
    with engineering when needed.
  - Utilize APIs and integration protocols (JSON, REST, SOAP) to
    configure workflows and integrate with CRM/ATS tools.
  - Write custom scripts to query databases and create reports
    for in-depth analysis and to demonstrate ROI to customers.
  
  Ideally, you'd have:
  
  - Experience:
    - 4+ years of software engineering experience.
    - Significant experience in AI/LLM application development,
      including building agents, integrations, workflows, and
      evaluating/improving their performance.
    - Experience setting up, configuring, and supporting ML
      Systems or AI Agents is a plus.
    - Experience in building LLM-based evaluation frameworks &
      conducting UATs with real customers.
    - Experience with prompt engineering techniques.
    - Demonstrated the ability to manage complex deployments &
      solution design for an enterprise customer independently
      with minimal guidance.
    - Familiarity with key support metrics (FRT, AHT, TAT, CSAT)
      and reporting.
    - Strong troubleshooting and problem-solving skills,
      especially in production environments. Ideal candidates
      should be able to troubleshoot ML performance issues &
      recommend solutions to improve accuracy metrics & other
      business KPIs.
    - Excellent communication skills to collaborate effectively
      with both technical and non-technical stakeholders.
  - Technical Skills:
    - Proficiency in Python & SQL scripting.
    - Understanding of Data Structures & Algorithms is a plus.
    - Experience with prompt engineering techniques.
    - Proficient at invoking platform APIs to retrieve or push
      data, configure workflows.
    - Familiarity with JSON, REST, SOAP or other integration
      protocols. Familiarity with integrating common CRMs/ATS
      tools would be a plus.
    - Data-driven evaluation skills, including setting up and
      interpreting A/A experiments.
    - Familiarity with logging, dashboard creation, and alerting
      tools.
  - Soft Skills:
    - Excellent communication skills to collaborate effectively
      with both technical and non-technical stakeholders.
    - Demonstrated ability to manage complex deployments &
      solution design for an enterprise customer
      independently.
    - Strong troubleshooting and problem-solving skills,
      especially in production environments.
    - Ownership & Initiative: Takes responsibility for ongoing
      workflow management and customer outcomes.
    - Curiosity & Continuous Learning: Actively explores new
      GenAI/automation techniques and best practices to
      enhance workflows.
    - Collaboration: Works effectively across multiple teams.
    - Customer Empathy: Prioritizes customer success criteria,
      ensuring solutions address real business needs.
  
  Ema Unlimited is an equal opportunity employer and is
  committed to providing equal employment opportunities to all
  employees and applicants for employment without regard to
  race, color, religion, sex, national origin, age,
  disability, sexual orientation, gender identity, or
  genetics.
posted_date: 2026-02-09
url: "https://builtin.com/job/senior-ai-applications-engineer/4802406"
source: Built In
