job_id: 7594026
title: AI Deployment Engineer
company: OpenAI
location: New Delhi, IND
work_type: FULL_TIME
level: Expert/Leader
skills:
  - Chatgpt
  - Generative Ai
  - JavaScript
  - Openai Api
  - Python
company_size: 224 Employees
description: |
  About the Team
  
  The AI Deployment Engineering team is responsible for
  ensuring the safe and effective deployment of Generative AI
  applications for developers and enterprises. We act as a
  trusted advisor and thought partner for our customers,
  working to build an effective backlog of GenAI use cases for
  their industry and drive them to production through strong
  technical guidance. As an AI Deployment Engineer, you’ll
  help the largest companies transform their business through
  solutions such as customer service, automated content
  generation, and novel applications that make use of our
  newest, most exciting models.
  
  About the Role
  
  We are looking for a driven solutions leader with a product
  mindset to partner with our customers and ensure they
  achieve tangible business value with GenAI. You will pair
  with senior customer leaders to establish a GenAI strategy
  and identify the highest value applications. You’ll then
  partner with their technical teams to move from prototype
  through production. You’ll take a holistic view of their
  needs and design an enterprise architecture using ChatGPT,
  OpenAI API, and other services to maximize customer value.
  You will collaborate closely with Sales, Solutions
  Engineering, Applied Research, and Product teams, and you
  will report to the Head of Technical Success, APAC.
  
  This role can be based in Delhi, Mumbai or Bangalore. We use
  a hybrid work model of 3 days in the office per week and
  offer relocation assistance to new employees
  
  In this role, you will:
  
  - Deeply embed with our most strategic platform customers as
    the technical lead, serving as their technical thought
    partner to ideate and build novel applications on our API.
  - Work with senior customer stakeholders to identify the best
    applications of GenAI in their industry and to
    build/qualify a comprehensive backlog to support their AI
    roadmap.
  - Intervene directly to accelerate customer time to value
    through building hands-on prototypes and/or by delivering
    impactful strategic guidance.
  - Forge and manage relationships with our customers’
    leadership and stakeholders to ensure the successful
    deployment and scale of their applications.
  - Contribute to our open-source developer and enterprise
    resources.
  - Scale the Solutions Architect function through sharing
    knowledge, codifying best practices, and publishing
    notebooks to our internal and external repositories.
  - Validate, synthesize, and deliver high-signal feedback to
    the Product and Research teams.
  
  You’ll thrive in this role if you:
  
  - Have 6+ years of technical consulting (or equivalent)
    experience, bridging technical teams and senior business
    stakeholders.
  - Are an effective and polished communicator who can translate
    business and technical topics to all audiences.
  - Have led complex implementations of Generative
    AI/traditional ML solutions and have knowledge of
    network/cloud architecture.
  - Have industry experience in programming languages like
    Python or Javascript.
  - Own problems end-to-end and are willing to pick up whatever
    knowledge you're missing to get the job done.
  - Have a humble attitude, an eagerness to help your
    colleagues, and a desire to do whatever it takes to make
    the team succeed.
  - Are an effective, high throughput operator who can drive
    multiple concurrent projects and prioritize ruthlessly.
  
  About OpenAI
  
  OpenAI is an AI research and deployment company dedicated to
  ensuring that general-purpose artificial intelligence
  benefits all of humanity. We push the boundaries of the
  capabilities of AI systems and seek to safely deploy them to
  the world through our products. AI is an extremely powerful
  tool that must be created with safety and human needs at its
  core, and to achieve our mission, we must encompass and
  value the many different perspectives, voices, and
  experiences that form the full spectrum of humanity.
  
  We are an equal opportunity employer, and we do not
  discriminate on the basis of race, religion, color, national
  origin, sex, sexual orientation, age, veteran status,
  disability, genetic information, or other applicable legally
  protected characteristic.
  
  For additional information, please see OpenAI’s Affirmative
  Action and Equal Employment Opportunity Policy Statement.
  
  Background checks for applicants will be administered in
  accordance with applicable law, and qualified applicants
  with arrest or conviction records will be considered for
  employment consistent with those laws, including the San
  Francisco Fair Chance Ordinance, the Los Angeles County Fair
  Chance Ordinance for Employers, and the California Fair
  Chance Act, for US-based candidates. For unincorporated Los
  Angeles County workers: we reasonably believe that criminal
  history may have a direct, adverse and negative relationship
  with the following job duties, potentially resulting in the
  withdrawal of a conditional offer of employment: protect
  computer hardware entrusted to you from theft, loss or
  damage; return all computer hardware in your possession
  (including the data contained therein) upon termination of
  employment or end of assignment; and maintain the
  confidentiality of proprietary, confidential, and non-public
  information. In addition, job duties require access to
  secure and protected information technology systems and
  related data security obligations.
  
  To notify OpenAI that you believe this job posting is non-
  compliant, please submit a report through this form. No
  response will be provided to inquiries unrelated to job
  posting compliance.
  
  We are committed to providing reasonable accommodations to
  applicants with disabilities, and requests can be made via
  this link.
  
  OpenAI Global Applicant Privacy Policy
  
  At OpenAI, we believe artificial intelligence has the
  potential to help people solve immense global challenges,
  and we want the upside of AI to be widely shared. Join us in
  shaping the future of technology.
industries:
  - Artificial Intelligence
  - Machine Learning
  - Generative AI
posted_date: 2026-02-15
url: "https://builtin.com/job/solutions-architect/7594026"
source: Built In
