job_id: 8047586
title: "Software Engineer | Python | AI Automation"
company: Miratech
location: Allpur, IND
work_type: FULL_TIME
level: Senior level
skills:
  - AI
  - AWS
  - Azure
  - DynamoDB
  - Lambda
  - Llms
  - Python
  - React
  - S3
company_size: 701 Employees
description: |
  Company Description
  
  Miratech helps visionaries change the world. We are a global
  IT services and consulting company that brings together
  enterprise and start-up innovation. Today, we support
  digital transformation for some of the world's largest
  enterprises. By partnering with both large and small
  players, we stay at the leading edge of technology, remain
  nimble even as a global leader, and create technology that
  helps our clients further enhance their business. We are a
  values driven organization and our culture of Relentless
  Performance has enabled over 99% of Miratech's engagements
  to succeed by meeting or exceeding our scope, schedule,
  and/or budget objectives since our inception in 1989.
  
  Miratech has coverage across five continents and operates in
  25 countries worldwide. Miratech retains over 1000 full-time
  professionals and has achieved sustained shareholder value
  growth exceeding 25% annually over many years.
  
  Job Description
  
  Miratech is seeking a talented and experienced Software
  Engineer with experience in Python and AI Automation to
  support our AI-powered Contact Center modernization
  initiatives. In this role, you will automate legacy routing
  systems using Large Language Models (LLMs), cloud-native
  tools, and modern scripting capabilities. Your work will
  directly impact the customer journey by developing
  intelligent, scalable solutions within highly regulated
  industries
  
  Responsibilities:
  
  - Automate existing contact center routing systems using AI
    agent technologies.
  - Design and implement cloud-native automation solutions using
    Python and LLMs.
  - Leverage AWS or Azure services such as storage, compute, and
    serverless functions to build scalable solutions.
  - Collaborate with cross-functional teams to ensure high-
    quality deliverables aligned with business requirements.
  - Create and maintain technical documentation to ensure
    continuity and clarity.
  - Provide timely updates to team leads and stakeholders on
    project progress
  
  Qualifications
  
  - 4+ years of hands-on experience with Python and a strong
    understanding of data structures and algorithms.
  - Experience working with LLMs and AI agents (e.g., prompt
    engineering, API integration, architecture).
  - Over 3 years of hands-on experience with AWS, including
    compute, storage, and serverless services (like DynamoDB,
    Lambda, S3, etc.).
  - Good Handon experience on UI- React.
  - Solid experience in automation scripting.
  - Strong understanding of SDLC and CI/CD best practices.
  - Excellent communication skills with the ability to
    collaborate effectively in a team environment.
  - Self-starter with strong analytical and problem-solving
    skills.
  
  Nice to have:
  
  - Experience with Node.js/Java
  - AWS Bedrock
  - Contact Center knowledge (Genesys Engage, Amazon Connect)
  
  We offer:
  
  - Culture of Relentless Performance: join an unstoppable
    technology development team with a 99% project success
    rate and more than 30% year-over-year revenue growth.
  - Competitive Pay and Benefits: enjoy a comprehensive
    compensation and benefits package, including health
    insurance, and a relocation program.
  - Work From Anywhere Culture: make the most of the flexibility
    that comes with remote work.
  - Growth Mindset: reap the benefits of a range of professional
    development opportunities, including certification
    programs, mentorship and talent investment programs,
    internal mobility and internship opportunities.
  - Global Impact: collaborate on impactful projects for top
    global clients and shape the future of industries.
  - Welcoming Multicultural Environment: be a part of a dynamic,
    global team and thrive in an inclusive and supportive work
    environment with open communication and regular team-
    building company social events.
  - Social Sustainability Values: join our sustainable business
    practices focused on five pillars, including IT education,
    community empowerment, fair operating practices,
    environmental sustainability, and gender equality.
  
  *Miratech is an equal opportunity employer and does not
  discriminate against any employee or applicant for
  employment on the basis of race, color, religion, sex,
  national origin, age, disability, veteran status, sexual
  orientation, gender identity, or any other protected status
  under applicable law.
  
  Additional Information
  
  All your information will be kept confidential according to
  EEO guidelines.
posted_date: 2026-02-11
url: "https://builtin.com/job/software-engineer-python-ai-automation/8047586"
source: Built In
