job_id: 8424466
title: Principal Engineer - Applications- AI/ML
company: Microchip Technology Inc.
location: Chennai, IND
work_type: FULL_TIME
level: Expert/Leader
skills:
  - AWS
  - Azure
  - Embedded C
  - GCP
  - I2C
  - Keras
  - Oci
  - Onnx
  - Python
  - PyTorch
company_size: 13,393 Employees
description: |
  Are you looking for a unique opportunity to be a part of
  something great? Want to join a 17,000-member team that
  works on the technology that powers the world around us?
  Looking for an atmosphere of trust, empowerment, respect,
  diversity, and communication? How about an opportunity to
  own a piece of a multi-billion dollar (with a B!) global
  organization? We offer all that and more at Microchip
  Technology Inc.
  
  People come to work at Microchip because we help design the
  technology that runs the world. They stay because our
  culture supports their growth and stability. They are
  challenged and driven by an incredible array of products and
  solutions with unlimited career potential. Microchip’s
  nationally-recognized Leadership Passage Programs support
  career growth where we proudly enroll over a thousand people
  annually. We take pride in our commitment to employee
  development, values-based decision making, and strong sense
  of community, driven by our Vision, Mission, and 11 Guiding
  Values; we affectionately refer to it as the Aggregate
  System and it’s won us countless awards for diversity and
  workplace excellence.
  
  Our company is built by dedicated team players who love to
  challenge the status quo; we did not achieve record revenue
  and over 30 years of quarterly profitability without a great
  team dedicated to empowering innovation. People like you.
  
  Visit our careers page to see what exciting opportunities
  and company perks await!
  
  Job Description:
  
  Microchip Technology Inc. is seeking Senior Applications
  Engineer to support the development of Edge AI / Machine
  Learning demonstrations on Microchip MCU, MPU, and FPGA
  platforms. This role focuses on creating, validating, and
  documenting reference designs and demonstrations that enable
  customers to deploy AI/ML workloads on resource-constrained
  embedded systems. The successful candidate will work closely
  with internal engineering, marketing, and field teams to
  enable customers through high-quality demos, example code,
  and technical collateral.
  
  Join our growing Edge AI team!
  
  Key Responsibilities:
  
  - Develop Embedded applications using Microchip AI offerings
    demonstrating product capabilities and features set with
    focus on Edge AI based solutions.
  - Develop reference solutions and proof of concept demos to
    assist customers in designing, developing &
    troubleshooting Edge AI applications like Sensor analytics
    implementation using AI on MCU platforms using TinyML.
  - Attend meetings with various stakeholders to understand the
    key customer issues and come up with solutions to solve
    them
  - Participate in Development, review and implementation of
    AI/ML applications, models and algorithms optimized for
    edge computing environments in our cloud-based development
    and application space.
  - Use AI models in various platforms using TFLite, Tensorflow,
    ONNX, Pytorch based technologies.
  - Provide presentations and trainings on technical topics to
    customers and other stakeholders
  - Provide feedback on improvements in Microchip’s hardware,
    software, tools and documentation targeting Edge AI
    solutions.
  - Work closely with product management to help define project
    requirements, milestones, and deliverables.
  - Work with software engineers to develop methodologies in
    gathering, applying and evaluating data for consumption by
    AI models running on Edge AI hardware.
  - Train and tune AI models for efficient execution on hardware
    platforms.
  - Utilize best practices in software development, including
    code reviews, unit testing, integration and continuous
    integration.
  - Stay up-to-date with the latest advancements in AI/ML and
    edge computing technologies to ensure our solutions remain
    at the cutting edge.
  - Work in a team environment, developing and fostering a
    culture of innovation and continuous improvement.
  
  Requirements/Qualifications:
  
  - Bachelor’s, Master’s degree in Computer Science, Electronics
    Engineering or related field.
  - 10+ years of total experience in Embedded design and
    development and at least 2+ years of specific AI/ML based
    application development.
  - Proficient knowledge in using machine learning development
    languages, tools and frameworks, such as the MPLAB Machine
    Learning Development Suite and Python AI/ML libraries
    using TensorFlow/TFLite, Pytorch, Keras, and ONNX.
  - Prior experience on any part of sensor analytics in real
    systems, including circuit breakers, consumer appliances,
    power supplies, gas / water leakage etc. would be an
    advantage.
  - Prior experience implementing tiny ML class algorithm on ARM
    M0 to M7 class MCU and / or similar performance DSP would
    be preferred.
  - Solid programming experience in Embedded C and use of
    Embedded Software frameworks/ solutions and OS
    fundamentals.
  - Good knowledge of one of more communication
    protocols/interfaces such as I2C, SPI, UART as well as
    other peripherals such as ADC/DAC, PWM, RTC, WDT,
    Timer/Counters
  - Experience in Motor control/ USB/ Graphics will be an added
    advantage
  - Application layer software development experience on
    embedded systems. Ability to translate complex technical
    concepts into
  - simplified examples.
  - Work experience on IDE tools like MPLAB IDE/ IAR Workbench/
    Keil MDK/ Atmel Studio or Linux environments
  - Exposure with RTOS/ Zephyr would be an added advantage
  - Team player with Strong written and verbal communication
    skills.
  - Must be highly motivated. Possess eager attitude toward
    learning new skills & technology.
  
  Preferred Qualifications:
  
  - Experience in TinyML or Edge AI workflows.
  - Familiarity with use of computing platforms (AWS, Azure,
    GCP, OCI) and edge-to-cloud integration.
  - Knowledge of data collection, preprocessing, and training
    neural networks in data centers.
  - Solid understanding of edge computing architectures,
    including IoT devices, embedded systems, and real-time
    processing.
  - Experience with edge computing platforms and optimizing
    AI/ML models for resource-constrained devices.
  - Knowledge of signal processing and analysis in an ML
    framework.
  - Knowledge of security and privacy considerations in edge
    computing and cyber security development and analysis
    methods using ISO-21434 workflow requirements.
  
  Travel Time:
  
  0% - 25%
  
  To all recruitment agencies: Microchip Technology Inc. does
  not accept unsolicited agency resumes. Please do not forward
  resumes to our recruiting team or other Microchip employees.
  Microchip is not responsible for any fees related to
  unsolicited resumes.
industries:
  - Hardware
  - Semiconductor
posted_date: 2026-02-19
url: "https://builtin.com/job/senior-engineer-ii-applications-ai-ml/8424466"
source: Built In
